<?php

namespace Seeders;

use App\Company;
use Illuminate\Database\Seeder;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $companies = collect(
            [
            "0verflow",
            "11 bit studios",
            "1C Company",
            "1-Up Studio",
            "2K Czech",
            "2K Games",
            "2K Sports",
            "343 Industries",
            "38 Studios",
            "3D Realms",
            "42 Entertainment",
            "4A Games",
            "5th Cell",
            "989 Studios",
            "Acclaim Entertainment",
            "Acclaim Studios Austin",
            "Accolade",
            "Access Games",
            "Access Software",
            "ACE Team",
            "Aces Studio",
            "Acquire",
            "Action Forms",
            "Active Gaming Media",
            "Activision",
            "Adventure Soft",
            "Akella",
            "Alfa System",
            "AlphaDream",
            "Amazon Game Studios",
            "Amazon Game Studios, Orange County",
            "Ambrella",
            "Amusement Vision",
            "Ancient",
            "Anino",
            "Ankama Games",
            "Appy Entertainment",
            "AQ Interactive",
            "Aquria",
            "Arc System Works",
            "Arcane Kids",
            "Arcen Games",
            "Arkane Studios",
            "Arkedo Studio",
            "ArenaNet",
            "Arika",
            "Art Co., Ltd",
            "Artdink",
            "ArtePiazza",
            "Artificial Studios",
            "Artoon",
            "Arzest",
            "Ascaron",
            "Asobo Studio",
            "Atari Interactive",
            "Atlus",
            "Atomic Planet Entertainment",
            "Attic Entertainment Software",
            "Avalanche Studios Group",
            "Aventurine SA",
            "Babaroga",
            "Backflip Studios",
            "Bandai Namco Entertainment",
            "Bauhaus Entertainment",
            "B.B. Studio",
            "Beenox",
            "Behaviour Interactive",
            "Behaviour Santiago",
            "Bethesda Game Studios",
            "Big Finish Games",
            "Big Huge Games",
            "BioWare",
            "The Bitmap Brothers",
            "Best Way",
            "Bits Studios",
            "Bizarre Creations",
            "Black Forest Games",
            "Black Isle Studios",
            "Black Rock Studio",
            "Black Wing Foundation",
            "Blitz Games Studios",
            "Blizzard Entertainment",
            "Bloober Team",
            "Bluepoint Games",
            "Blueside",
            "Blue Fang Games",
            "Blue Tongue Entertainment",
            "Bluehole",
            "Bohemia Interactive",
            "Boss Fight Entertainment",
            "Boss Key Productions",
            "BreakAway Games",
            "Brøderbund",
            "Bugbear Entertainment",
            "Bullfrog Productions",
            "Bungie",
            "Camelot Software Planning",
            "Capcom",
            "Capcom Vancouver",
            "Carbine Studios",
            "Cattle Call",
            "Cauldron",
            "Cave",
            "Cavia",
            "CCP Games",
            "CD Projekt Red",
            "Certain Affinity",
            "Chair Entertainment",
            "Chunsoft",
            "Cing",
            "Clap Hanz",
            "Climax Entertainment",
            "Climax Studios",
            "Clover Studio",
            "Coded Illusions",
            "Codemasters",
            "Coffee Stain Studios",
            "Cohort Studios",
            "Coktel Vision",
            "Colossal Order",
            "Compile Heart",
            "Compulsion Games",
            "Core Design",
            "Crafts &amp; Meister",
            "Crawfish Interactive",
            "Creat Studios",
            "Creative Assembly",
            "Creatures",
            "Criterion Games",
            "Croteam",
            "Cryo Interactive",
            "Culture Brain Excel",
            "Crea-Tech",
            "Cryptic Studios",
            "Crystal Dynamics",
            "Crytek",
            "Crytek UK",
            "Cyan Worlds",
            "Cyanide",
            "CyberConnect2",
            "Cyberlore Studios",
            "CyberStep",
            "Cygames",
            "Dambuster Studios",
            "Danger Close Games",
            "Day 1 Studios",
            "Daybreak Game Company",
            "Deadline Games",
            "Deck13",
            "Deep Silver Volition",
            "Demiurge Studios",
            "DeNA",
            "devCAT Studios",
            "Dhruva Interactive",
            "Die Gute Fabrik",
            "Digital Extremes",
            "Digital Eclipse",
            "Digitalmindsoft",
            "Digital Reality",
            "Dimps",
            "Disney Interactive Studios",
            "Dontnod Entertainment",
            "DotEmu",
            "Double Fine Productions",
            "Dynamix",
            "Dovetail Games",
            "The Dovetail Group",
            "EA Black Box",
            "EA Digital Illusions CE",
            "EA Gothenburg",
            "EA Vancouver",
            "Eat Sleep Play",
            "Eko Software",
            "Egosoft",
            "Eden Games",
            "Eighting",
            "Electronic Arts",
            "Elemental Games",
            "Engine Software",
            "Ensemble Studios",
            "Epic Games",
            "Epics",
            "Epicenter Studios",
            "Epyx",
            "ESA",
            "Étranges Libellules",
            "Eugen Systems",
            "Eurocom",
            "Evolution Studios",
            "Examu",
            "Eyedentity Games",
            "F4",
            "Facepunch Studios",
            "FarSight Studios",
            "FASA Studio",
            "Fatshark",
            "feelplus",
            "Felistella",
            "Firaxis Games",
            "Firefly Studios",
            "Firesprite",
            "First Star Software",
            "Flagship Studios",
            "Flight-Plan",
            "Flying Wild Hog",
            "Focus Home Interactive",
            "Foundation 9 Entertainment",
            "Fox Digital Entertainment",
            "FoxNext",
            "Frictional Games",
            "Frogwares",
            "FromSoftware",
            "Frontier Developments",
            "Frozenbyte",
            "FTL Games",
            "FUN Labs",
            "Funcom",
            "FuRyu",
            "Futuremark",
            "Gaijin Entertainment",
            "Game Arts",
            "Game Freak",
            "GameHouse",
            "Gameloft",
            "Ganbarion",
            "Gearbox Software",
            "Geewa",
            "Genius Sonority",
            "Genki",
            "Glu Mobile",
            "Gogii Games",
            "Good-Feel",
            "Granzella",
            "Grasshopper Manufacture",
            "Gravity",
            "Gray Matter Interactive",
            "Gremlin Interactive",
            "Grezzo",
            "Grinding Gear Games",
            "Griptonite Games",
            "GSC Game World",
            "Guerrilla Cambridge",
            "Guerrilla Games",
            "Gunfire Games",
            "GungHo Online Entertainment",
            "Gust",
            "Haemimont Games",
            "HAL Laboratory",
            "Halfbrick",
            "Hanaho",
            "h.a.n.d.",
            "Hangar 13",
            "Harebrained Schemes",
            "Harmonix Music Systems",
            "Headstrong Games",
            "Heartbeat",
            "HB Studios",
            "HeroCraft",
            "High Impact Games",
            "High Moon Studios",
            "High Voltage Software",
            "Hoplon Infotainment",
            "Hothead Games",
            "Housemarque",
            "Hudson Soft",
            "Human Entertainment",
            "Human Head Studios",
            "Humongous Entertainment",
            "Hyperion Entertainment",
            "Ice-Pick Lodge",
            "id Software",
            "Idea Factory",
            "Idol Minds",
            "Imageepoch",
            "Image &amp; Form",
            "Imagineer",
            "Infinity Ward",
            "Infocom",
            "Incognito Entertainment",
            "Incredible Technologies",
            "indieszero",
            "Innerloop Studios",
            "Insomniac Games",
            "Intelligent Systems",
            "Interplay Entertainment",
            "Introversion Software",
            "inXile Entertainment",
            "IO Interactive",
            "Ion Storm",
            "Ion Storm",
            "Irem",
            "Iron Galaxy Studios",
            "Iron Lore Entertainment",
            "Irrational Games",
            "Ivory Tower",
            "Jadestone Group",
            "Jagex",
            "Jaleco",
            "Jam City",
            "Javaground",
            "Jupiter",
            "JV Games",
            "Kairosoft",
            "Kalypso Media",
            "Kaos Studios",
            "Keen Software House",
            "Kesmai",
            "Kiloo Games",
            "King",
            "Koei Tecmo Games",
            "KOG Studios",
            "Kojima Productions",
            "Konami",
            "Kongzhong",
            "Krome Studios",
            "Krome Studios Melbourne",
            "Kuju Entertainment",
            "Kunos Simulazioni",
            "Kush Games",
            "Kuma Reality Games",
            "Kylotonn",
            "Larian Studios",
            "Legacy Interactive",
            "Legend Entertainment",
            "Legendo Entertainment",
            "Level-5",
            "Lift London",
            "Limbic Entertainment",
            "Lionhead Studios",
            "Liquid Entertainment",
            "Little Green Men Games",
            "LK Avalon",
            "Llamasoft",
            "Linden Lab",
            "Locomotive Games",
            "Looking Glass Studios",
            "Love-de-Lic",
            "LucasArts",
            "Luma Arcade",
            "Luxoflux",
            "MachineGames",
            "Magenta Software",
            "MAGES.",
            "Majesco Entertainment",
            "Marvelous",
            "Massive Entertainment",
            "Masthead Studios",
            "Matrix Software",
            "Maxis",
            "Mean Hamster Software",
            "Media Molecule",
            "Media.Vision",
            "Mediatonic",
            "MegaZebra",
            "Mercury Steam",
            "Metropolis Software",
            "MicroProse Software",
            "MTO",
            "Microsoft Casual Games",
            "Midway Games",
            "Midway Studios – Newcastle",
            "Milestone",
            "Milestone srl",
            "Mimimi Games",
            "Mistwalker",
            "Mitchell Corporation",
            "MLB Advanced Media",
            "Mode 7 Games",
            "Mojang AB",
            "Monolith Productions",
            "Monolith Soft",
            "Monster Games",
            "Monte Cristo",
            "Moon Studios",
            "Mythic Entertainment",
            "Nadeo",
            "Namco Tales Studio",
            "Nanobit",
            "NAPS team",
            "Natsume",
            "NaturalMotion",
            "Naughty Dog",
            "NCSoft",
            "NDcube",
            "NDOORS Corporation",
            "Neko Entertainment",
            "Nerve Software",
            "NetDevil",
            "NetDragon Websoft",
            "NetEase",
            "NetherRealm Studios",
            "Neverland",
            "Neversoft",
            "Nevosoft",
            "New World Computing",
            "New World Interactive",
            "Nexon",
            "Next Level Games",
            "NGD Studios",
            "Niantic",
            "Nibris",
            "Nicalis",
            "Nihon Falcom",
            "Nikita Online",
            "Ninjabee",
            "Ninja Theory",
            "Nintendo",
            "Nippon Ichi Software",
            "Nival",
            "Nordeus",
            "NovaLogic",
            "Novarama",
            "Now Production",
            "n-Space",
            "Obsidian Entertainment",
            "Oddworld Inhabitants",
            "Omega Force",
            "Origin Systems",
            "OtherSide Entertainment",
            "Outfit7",
            "Outrage Entertainment",
            "Overkill Software",
            "Oxygen Studios",
            "Page 44 Studios",
            "Pangea Software",
            "People Can Fly",
            "Project Sora",
            "Purple Lamp Studios",
            "Papaya Studio",
            "Project Soul",
            "Panther Games Pty Ltd",
            "Paradox Development Studio",
            "Parallax Software",
            "Pandemic Studios",
            "Pendulo Studios",
            "Penguin Software",
            "Perfect World",
            "Petroglyph",
            "Phantagram",
            "Phenomic Game Development",
            "Pipeworks Studios",
            "Piranha Bytes",
            "Piranha Games",
            "Pi Studios",
            "Pivotal Games",
            "Pixel Federation",
            "Playdom",
            "Playfish",
            "PlayFirst",
            "Playground Games",
            "PlatinumGames",
            "Polyphony Digital",
            "PopCap Games",
            "Press Play",
            "Psyonix",
            "Punch Entertainment",
            "Pyro Mobile",
            "Q Entertainment",
            "Q-Games",
            "Quantic Dream",
            "Quest Corporation",
            "Radical Entertainment",
            "Rage Games",
            "Rainbow Studios",
            "Rare",
            "Raven Software",
            "Ready at Dawn",
            "Red Entertainment",
            "Reality Pump Studios",
            "Realtime Associates",
            "Realtime Worlds",
            "Rebellion Developments",
            "Rebellion Warwick",
            "RedLynx",
            "Red Thread Games",
            "Red Storm Entertainment",
            "RedTribe",
            "Reflexive Entertainment",
            "Relic Entertainment",
            "Remedy Entertainment",
            "Respawn Entertainment",
            "Reto-Moto",
            "Retro Studios",
            "Revolution Software",
            "Riot Games",
            "Rising Star Games",
            "Robot Entertainment",
            "Rockstar Games",
            "Rocksteady Studios",
            "Robinson Technologies",
            "Rovio Entertainment",
            "Ruffian Games",
            "Runic Games",
            "Running with Scissors",
            "Saber Interactive",
            "Sand Grain Studios",
            "Sandlot",
            "Sanzaru Games",
            "Sir-Tech",
            "Schell Games",
            "SCS Software",
            "Sega",
            "SEGA Interactive R&amp;D Division 1",
            "SEGA Interactive R&amp;D Division 2",
            "Sega AM3",
            "Sega CS Research and Development No. 2",
            "Sega Sports R&amp;D",
            "Sensible Software",
            "Shift",
            "SIE Bend Studio",
            "SIE San Mateo Studio",
            "SIE Japan Studio",
            "SIE London Studio",
            "SIE San Diego Studio",
            "SIE Santa Monica Studio",
            "SCE Studio Liverpool",
            "SIE Worldwide Studios",
            "SingleTrac",
            "Shengqu Games",
            "Sherman3D",
            "Shin'en Multimedia",
            "Sierra Entertainment",
            "Silicon Knights",
            "Silicon Studio",
            "Simtex",
            "skip Ltd.",
            "Slant Six Games",
            "Sledgehammer Games",
            "Snail",
            "Slightly Mad Studios",
            "Slipgate Ironworks",
            "Slitherine Software",
            "Smilegate",
            "SNK",
            "Sobee Studios",
            "Snowblind Studios",
            "Software 2000",
            "Sony Interactive Entertainment",
            "Sora Ltd.",
            "Spellbound Entertainment",
            "Spiders",
            "Spike",
            "Spike Chunsoft",
            "Spil Games",
            "Splash Damage",
            "Sproing Interactive Media",
            "Square Enix",
            "Squad",
            "Stainless Games",
            "Stainless Steel Studios",
            "Starbreeze Studios",
            "Stardock",
            "Sting Entertainment",
            "Strategic Simulations",
            "Stoic Studio",
            "Strawdog Studios",
            "Straylight Studios",
            "Streamline Studios",
            "Success",
            "Sucker Punch Productions",
            "Sumo Digital",
            "Supercell",
            "Supermassive Games",
            "SuperVillain Studios",
            "Survios",
            "Studio Wildcard",
            "Swingin' Ape Studios",
            "StormRegion",
            "Sunstorm Interactive",
            "Syn Sophia",
            "SystemSoft Beta",
            "Taito",
            "Tango Gameworks",
            "Tag Games",
            "TaleWorlds Entertainment",
            "Tamsoft",
            "T&amp;E Soft",
            "Tantrumedia",
            "Tantalus Media",
            "Tarsier Studios",
            "Tate Multimedia",
            "Team17",
            "Team Bondi",
            "Team Ico",
            "Team Ninja",
            "Techland",
            "Tecmo",
            "Telltale Games",
            "Tencent",
            "Tencent Games",
            "Tequila Works",
            "Terminal Reality",
            "Tetris Online",
            "Teyon",
            "Thatgamecompany",
            "The Chinese Room",
            "The Coalition",
            "The Farm 51",
            "The Initiative",
            "THQ",
            "THQ Nordic",
            "Three Fields Entertainment",
            "Three Rings Design",
            "TimeGate Studios",
            "TiMi Studios",
            "Toaplan",
            "ToeJam &amp; Earl Productions",
            "Tokyo RPG Factory",
            "TopWare Interactive",
            "Torpex Games",
            "Torus Games",
            "Tose",
            "Toys for Bob",
            "Trapdoor",
            "Transmission Games",
            "Traveller's Tales",
            "Treyarch",
            "Treasure",
            "tri-Ace",
            "tri-Crescendo",
            "Trion Worlds",
            "Tripwire Interactive",
            "Triumph Studios",
            "Turn 10 Studios",
            "Turtle Rock Studios",
            "Two Point Studios",
            "Two Tribes",
            "Typhoon Games (HK)",
            "Ubisoft",
            "Ubisoft Blue Byte",
            "Ubisoft Reflections",
            "UEP Systems",
            "Ultimate Play the Game",
            "Undead Labs",
            "United Front Games",
            "United Game Artists",
            "Universomo",
            "Valve",
            "Vanillaware",
            "Vanpool",
            "Venan Entertainment",
            "Vicarious Visions",
            "Vigil Games",
            "Virtual Heroes",
            "Virtuos",
            "Visceral Games",
            "Visual Concepts",
            "Vostok Games",
            "VoxelStorm",
            "Wahoo Studios",
            "Warhorse Studios",
            "Wargaming",
            "Wargaming Saint Petersburg",
            "Wargaming Seattle",
            "Warner Bros. Interactive Entertainment",
            "WB Games Boston",
            "WB Games - Avalanche",
            "Webfoot Technologies",
            "WeMade",
            "Westone Bit Entertainment",
            "Westwood Studios",
            "Wideload Games",
            "Wildfire Studios",
            "Wizet studio",
            "Wolfire Games",
            "World Forge",
            "Xbox Game Studios",
            "XPEC Entertainment",
            "Yager Development",
            "Yuke's",
            "ZeniMax Online Studios",
            "Zipper Interactive",
            "Zombie Studios",
            "ZootFly",
            "Zynga"
            ]
        );

        $companies->map(
            fn ($name) => factory(Company::class)->create(
                [
                'name' => $name
                ]
            )
        );
    }
}
