<?php

namespace Seeders;

use App\Models\Publisher;
use Illuminate\Database\Seeder;

class PublisherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $publishers = collect(
            [
            "07th Expansion",
            "11 bit studios",
            "1C Company",
            "2K Games",
            "3D Realms",
            "The 3DO Company",
            "505 Games",
            "5pb.",
            "7th Level",
            "A&F Software",
            "Aackosoft",
            "Aardvark Software",
            "ABC Software",
            "Absolute Entertainment",
            "Access Software",
//            "Acclaim Entertainment",
//            "Accolade",
//            "Acornsoft",
//            "Acquire",
//            "Active Gaming Media AGM",
//            "Activision",
//            "Activision Blizzard",
//            "Addictive Games",
//            "The Adventure Company",
//            "Adventure International",
//            "Adventure Soft",
//            "Affect",
//            "Agatsuma Entertainment",
//            "Âge",
//            "AGEod",
//            "Agetec",
//            "Akabeisoft2",
//            "Akella",
//            "Akupara Games",
//            "Aksys",
//            "ALcot",
//            "Alawar",
//            "AliceSoft",
//            "AlphaDream",
//            "ADK",
//            "Alchemist",
//            "Alligata",
//            "Allumer",
//            "Alten8",
//            "Alternative Software",
//            "American Game Cartridges",
//            "American Laser Games",
//            "American Video Entertainment",
//            "Amplitude Studios",
//            "Amsoft",
//            "ANALOG Software",
//            "Antic Software",
//            "Anuman",
//            "APF Electronics Inc.",
//            "Apogee Software",
//            "Apple Inc.",
//            "Aquaplus",
//            "AQ Interactive",
//            "Arcadia Systems",
//            "Arcen Games",
//            "Arc System Works",
//            "Argus Press",
//            "Arika",
//            "Ariolasoft",
//            "Armor Games",
//            "Arsys Software",
//            "Artdink",
//            "Artic Computing",
//            "Arush Entertainment",
//            "Arxel Tribe",
//            "Ascaron",
//            "ASC Games",
//            "Asmik Corporation of America",
//            "Aspyr Media",
//            "Astragon",
//            "Atari, Inc",
//            "Atari, SA",
//            "Athena",
//            "Atlantis Software",
//            "AQ Interactive",
//            "Artech Digital Entertainment",
//            "ASCII Corporation",
//            "Atlus",
//            "Attic Entertainment Software",
//            "Audiogenic Limited",
//            "August",
//            "Auran Development",
//            "Automata UK",
//            "Autumn Games",
//            "Avalon Hill",
//            "Aventuras AD",
//            "Aventurine SA",
//            "BAM! Entertainment",
//            "Bandai Games",
//            "Bandai Namco Entertainment",
//            "Banpresto",
//            "BBC Multimedia",
//            "Beagle Bros",
//            "Bergsala Lightweight",
//            "Berkeley Systems",
//            "Bethesda Softworks",
//            "Beyond Software",
//            "Big Fish Games",
//            "Big Five Software",
//            "Black Bean Games",
//            "Blue Byte",
//            "Broderbund",
//            "Black Legend",
//            "Blizzard Entertainment",
//            "Blue Ribbon",
//            "Bohemia Interactive",
//            "Box Office, Inc.",
//            "Brash Entertainment",
//            "Broccoli",
//            "Bug-Byte",
//            "Bubble Bus Software",
//            "BudgeCo",
//            "Bullet-Proof Software",
//            "Bungie",
//            "C&E",
//            "California Dreams",
//            "California Pacific Computer Company",
//            "Camerica",
//            "Canal+ Multimedia",
//            "Candy Soft",
//            "Capcom",
//            "Capstone Software",
//            "Caramel Box",
//            "Carry Lab",
//            "Casady & Greene",
//            "Cases Computer Simulations",
//            "Cave",
//            "CBS Electronics",
//            "CD Projekt Red",
//            "CDS Software",
//            "CDV Software Entertainment AG",
//            "Centuri",
//            "ChessBase",
//            "Cinemax",
//            "CI Games",
//            "Cinematronics",
//            "Cinemaware",
//            "Circus",
//            "Club Kidsoft",
//            "The Coca-Cola Company",
//            "Codemasters",
//            "Coktel Vision",
//            "Coleco",
//            "Color Dreams",
//            "CommaVid",
//            "Commercial Data Systems",
//            "Commodore",
//            "Compile",
//            "Compile Heart",
//            "CompuServe",
//            "Computer and Video Games",
//            "Conspiracy Entertainment",
//            "Core Design",
//            "Cosmi Corporation",
//            "Crave Entertainment",
//            "Creative Computing",
//            "Creatures",
//            "Crimson Cow",
//            "CRL Group",
//            "Cronosoft",
//            "Culture Brain Excel",
//            "Cryo Interactive",
//            "Crystal Computing",
//            "Crystal Dynamics",
//            "Crytek",
//            "Cyberdreams",
//            "Cybersoft",
//            "D3 Publisher",
//            "Daedalic Entertainment",
//            "DarXabre",
//            "Datamost",
//            "Datam Polystar",
//            "Datasoft",
//            "Data Age",
//            "Data Becker",
//            "Data East",
//            "Davidson & Associates",
//            "Davilex Games",
//            "Davka",
//            "Daybreak Game Company",
//            "dB-SOFT",
//            "Deep Silver",
//            "Delphine Software International",
//            "Delta 4",
//            "Destination Software",
//            "Destineer",
//            "Devolver Digital",
//            "Digital Fantasia",
//            "Digital Integration",
//            "Digital Jesters",
//            "Digital Leisure",
//            "Digital Pictures",
//            "Dinamic Multimedia",
//            "Dinamic Software",
//            "Disney Interactive Studios",
//            "DK'Tronics",
//            "Domark",
//            "Double Fine",
//            "Dovetail Games",
//            "Dragon Data",
//            "DreamCatcher Games",
//            "DreamWorks Interactive",
//            "DROsoft",
//            "Dtp entertainment",
//            "Dynamic Planning",
//            "Dynamix",
//            "EasyGameStation",
//            "Ecole Software",
//            "Edu-Ware",
//            "eGames",
//            "Electric Dreams Software",
//            "Electronic Arts",
//            "Electronic Arts Victor",
//            "Electro Brain",
//            "The Elektrik Keyboard",
//            "ELF Corporation",
//            "Elite Systems",
//            "Empire Interactive",
//            "English Software",
//            "Enix",
//            "Enlight Software",
//            "Enterbrain",
//            "Durell Software",
//            "Edge Games",
//            "Eighting",
//            "Electric Transit",
//            "Emerald Software",
//            "Encore, Inc.",
//            "Entertainment Software Publishing",
//            "En Masse Entertainment",
//            "Eolith",
//            "Eon Digital Entertainment",
//            "Epic Games",
//            "Epoch Co.",
//            "Epyx",
//            "ERE Informatique",
//            "ESA",
//            "Europress",
//            "Eushully",
//            "Examu",
//            "Exidy",
//            "FASA",
//            "Fabtek",
//            "Fandom",
//            "Fairchild Semiconductor",
//            "Family Soft",
//            "Fantasy Software",
//            "Faster Than Light",
//            "Fathammer",
//            "Firebird Software",
//            "First Star Software",
//            "Feral Interactive",
//            "Fill-in-Cafe",
//            "Fisher Price",
//            "Fishtank Interactive",
//            "Flair Software",
//            "Flight-Plan",
//            "Flying Edge",
//            "Focus Home Interactive",
//            "Focus Multimedia",
//            "FormGen",
//            "The Fourth Dimension",
//            "Fox Interactive",
//            "Freeverse Software",
//            "French Bread",
//            "Froggo",
//            "FromSoftware",
//            "Front Wing",
//            "FTL Games",
//            "Fujisankei Communications International",
//            "Fujitsu",
//            "Full On Games",
//            "Funcom",
//            "Future Games",
//            "Fuuki",
//            "G-Collections",
//            "G.rev",
//            "Gaelco",
//            "Gaijinworks",
//            "Gainax",
//            "Gakken",
//            "Gamecock",
//            "Gameloft",
//            "Games by Apollo",
//            "Games Workshop",
//            "GameTek",
//            "Game Arts",
//            "The Game Factory",
//            "Game Park",
//            "Game Studio",
//            "Gargoyle Games",
//            "Gathering of Developers",
//            "Gearbox Software",
//            "General Entertainment",
//            "Genki",
//            "Ghostlight",
//            "Global Star Software",
//            "Gathering of Developers",
//            "Gebelli Software",
//            "Giga",
//            "Gizmondo",
//            "Global A Entertainment",
//            "Global VR",
//            "GN Software",
//            "GOG Ltd",
//            "Gogii Games",
//            "Gotham Games",
//            "Gottlieb",
//            "Got Game Entertainment",
//            "Grandslam Entertainment",
//            "Graphsim Entertainment",
//            "Gravity",
//            "Great Wave Software",
//            "Gremlin Industries",
//            "Gremlin Interactive",
//            "Grolier Interactive Inc",
//            "Groove Games",
//            "GSC World Publishing",
//            "GTE Interactive Media",
//            "GT Interactive",
//            "GungHo Online Entertainment",
//            "Gust Co. Ltd.",
//            "Hacker International",
//            "Haikuo Soft",
//            "HAL Laboratory",
//            "Hamster Corporation",
//            "HanbitSoft",
//            "Hasbro Interactive",
//            "Hect",
//            "HeR Interactive",
//            "Heureka-Klett",
//            "Hi Tech Expressions",
//            "Hewson Consultants",
//            "Hirameki",
//            "Hodder & Stoughton",
//            "Home Entertainment Suppliers",
//            "Hooksoft",
//            "HopeLab",
//            "Houghton Mifflin Harcourt",
//            "Hudson Soft",
//            "Human Engineered Software",
//            "Human Entertainment",
//            "Humble Bundle",
//            "HummingBirdSoft",
//            "Humongous Entertainment",
//            "IBM",
//            "Iceberg Interactive",
//            "ICOM Simulations",
//            "Idea Factory",
//            "id Software",
//            "Ignition Entertainment",
//            "Illusion Soft",
//            "Imageepoch",
//            "Image Works",
//            "Imagic",
//            "Imagine Software",
//            "Impressions Games",
//            "Incentive Software",
//            "Incredible Technologies",
//            "index+",
//            "indiePub Entertainment",
//            "Infocom",
//            "Infogrames",
//            "Innerprise Software",
//            "Inscape",
//            "Intellivision Productions",
//            "Interactive Magic",
//            "Interceptor Micros",
//            "Interchannel",
//            "International Games System",
//            "Interplay Entertainment",
//            "Introversion Software",
//            "INTV Corporation",
//            "inXile Entertainment",
//            "iQue",
//            "Irem",
//            "ITE Media",
//            "J.K. Greye Software",
//            "Jaleco",
//            "JAST USA",
//            "Jester Interactive",
//            "Johnson & Johnson",
//            "JoWooD Productions",
//            "JumpStart Games",
//            "K2 Network",
//            "Kalisto Entertainment",
//            "Kalypso Media",
//            "Kaneko",
//            "Kaypro",
//            "Kemco",
//            "King Games",
//            "KID",
//            "Kingsoft",
//            "King Records",
//            "Koch Media",
//            "Kodansha",
//            "Koei",
//            "Koei Tecmo",
//            "Kogado Studio",
//            "Konami",
//            "Krisalis Software",
//            "KSS",
//            "Kure Software Koubou",
//            "La'cryma",
//            "Lankhor",
//            "Le Lombard",
//            "Legacy Interactive",
//            "Legendo Entertainment",
//            "Legend Entertainment",
//            "Lego Interactive",
//            "Leland Corporation",
//            "Level-5",
//            "Level 9 Computing",
//            "Linux Game Publishing",
//            "Lighthouse Interactive",
//            "LJN",
//            "LK Avalon",
//            "Llamasoft",
//            "Lock 'n Load Publishing",
//            "Logotron Ltd",
//            "Loki Software",
//            "Loriciel",
//            "LucasArts",
//            "Lump of Sugar",
//            "MacPlay",
//            "MacSoft",
//            "Mad Catz",
//            "Magical Company",
//            "Magnavox",
//            "Mr Chip Software",
//            "magnussoft",
//            "Mandarin Software",
//            "MangaGamer",
//            "Martech",
//            "Majesco Entertainment",
//            "Marvelous",
//            "Marvelous Entertainment",
//            "Masaya",
//            "Mastertronic",
//            "Mastiff",
//            "Matrix Games",
//            "Mattel",
//            "Maximum Games",
//            "Maxis",
//            "Max Design",
//            "MC2 France",
//            "MC Lothlorien",
//            "MECC",
//            "MediaWorks",
//            "Media Factory",
//            "Media Rings",
//            "Mega Enterprise",
//            "Melbourne House",
//            "Meldac",
//            "Metro3D, Inc.",
//            "Metropolis Software",
//            "MGM Interactive",
//            "Microdeal",
//            "Microids",
//            "MicroIllusions",
//            "Micronet co., Ltd.",
//            "MicroProse",
//            "Microsoft",
//            "Microsphere",
//            "Microcabin",
//            "Micrografx",
//            "MicroGraphic Image",
//            "Micro Genius",
//            "Micro Power",
//            "Midas Interactive Entertainment",
//            "Midway Games",
//            "Midway Manufacturing",
//            "Mikro-Gen",
//            "MileStone Inc.",
//            "Millennium Interactive",
//            "Milton Bradley Company",
//            "Minato Soft",
//            "Mindcraft",
//            "Mindscape",
//            "Minori",
//            "Mirrorsoft",
//            "Mitchell Corporation",
//            "Mode 7 Games",
//            "Mojang",
//            "Monolith Productions",
//            "Monte Cristo",
//            "Moonstone",
//            "Mosaic Publishing",
//            "MOSS",
//            "Motown Games",
//            "Mountain King Studios",
//            "MTO",
//            "MTV Games",
//            "Mud Duck Productions",
//            "Muse Software",
//            "MumboJumbo",
//            "Mystique",
//            "Nacon",
//            "Namco",
//            "Natsume Co Ltd",
//            "Natsume Inc",
//            "Navel",
//            "Naxat Soft",
//            "NBCUniversal",
//            "NCsoft",
//            "NEC Corporation",
//            "Neko Entertainment",
//            "Netdragon",
//            "Netease",
//            "New Generation Software",
//            "NewKidCo",
//            "New World Computing",
//            "Nexon",
//            "Nihon Falcom",
//            "Nintendo",
//            "Nippon Ichi Software",
//            "Nihon Bussan",
//            "Nitroplus",
//            "Novagen Software",
//            "Nokia",
//            "Nordcurrent",
//            "NovaLogic",
//            "NTDEC",
//            "Nutting Associates",
//            "O3 Entertainment",
//            "Ocean Software",
//            "Ocean State Publishing",
//            "Oculus Studios",
//            "Odin Computer Graphics",
//            "Opera Soft",
//            "Orbital Media",
//            "Origin Systems",
//            "Orion Interactive",
//            "Out of the Park Developments",
//            "0verflow",
//            "Oxygen Games",
//            "OziSoft",
//            "Pacific Novelty",
//            "Pack-In-Video",
//            "Palace Software",
//            "Palette",
//            "Panasonic",
//            "Panda Entertainment",
//            "Panesian Taiwan",
//            "Panther Games",
//            "Panther Software",
//            "Paradox Interactive",
//            "Paragon Software",
//            "Parker Brothers",
//            "Parsoft Interactive",
//            "Penguin Software",
//            "Pentavision",
//            "Perfect World",
//            "Personal Software Services",
//            "Petit Ferret",
//            "Petroglyph Games",
//            "PF Magic",
//            "Phantagram",
//            "Philips",
//            "Pionesoft",
//            "Piranha Games",
//            "Piranha Interactive Publishing",
//            "PlayFirst",
//            "Playlogic Entertainment, Inc.",
//            "Playmates Toys",
//            "The Pokémon Company",
//            "Pony Canyon",
//            "PopCap Games",
//            "Positech Games",
//            "Presto Studios",
//            "PrincessSoft",
//            "Prism Leisure Corporation",
//            "Private Division",
//            "Probe Software",
//            "Programma International",
//            "Prototype",
//            "Psygnosis",
//            "Psikyo",
//            "Psytronik Software",
//            "Pulltop",
//            "Purple Moon",
//            "Purple software",
//            "Quality Software",
//            "Quantum Axcess",
//            "Quantum Quality Productions",
//            "Quest Corporation",
//            "Quicksilva",
//            "QuinRose",
//            "Quintet",
//            "Qute",
//            "Q Entertainment",
//            "R2Games",
//            "Rabbit Software",
//            "Radica Games",
//            "Rage Software",
//            "Rainbird Software",
//            "Rainbow Arts",
//            "Rare",
//            "Ravensburger Interactive",
//            "Raw Fury",
//            "Raw Thrills",
//            "Red Ant Enterprises",
//            "Red Entertainment",
//            "RedOctane",
//            "Red Orb Entertainment",
//            "Red Shift",
//            "Red Storm Entertainment",
//            "Regista",
//            "reLINE Software",
//            "Renegade Software",
//            "Renovation Products",
//            "Richard Shepherd Software",
//            "Right Stuff",
//            "Riot Games",
//            "Ripcord Games",
//            "Rising Star Games",
//            "Riverhillsoft",
//            "Rock-Ola",
//            "Rockstar Games",
//            "Romstar",
//            "Romtech",
//            "Rovio Entertainment",
//            "RTL Group",
//            "RuneSoft",
//            "Saga Planets",
//            "Sammy Studios",
//            "Samsung",
//            "Sanctuary Woods",
//            "Scavenger, Inc.",
//            "Scopely",
//            "SCi Games",
//            "SCS Software",
//            "Safari Software",
//            "Scholastic",
//            "Sears",
//            "Sega",
//            "Seibu Kaihatsu",
//            "SETA Corporation",
//            "Seven45 Studios",
//            "Shadow Tor Studios",
//            "Shanda",
//            "Sharp Corporation",
//            "Shengqu Games",
//            "Sherston Software",
//            "Shoeisha",
//            "Shogakukan",
//            "Sierra Entertainment",
//            "Silicon Beach Software",
//            "Silmarils",
//            "Simon & Schuster Interactive",
//            "SIMS Co., Ltd.",
//            "Simulations Canada",
//            "Sinclair Research Ltd.",
//            "Sirius Software",
//            "Sir-Tech",
//            "Slitherine",
//            "SNK",
//            "Soedesco",
//            "SOFEL",
//            "Soft-World",
//            "Softape",
//            "Softdisk",
//            "SoftKey",
//            "Softek International Ltd",
//            "SoftSide",
//            "Softstar",
//            "Software 2000",
//            "Software Dynamics",
//            "Software Projects",
//            "Sony Imagesoft",
//            "Sony Interactive Entertainment",
//            "Sony Pictures Digital",
//            "SouthPeak Games",
//            "Spectral Associates",
//            "Spectravideo",
//            "Spectrum HoloByte",
//            "Spike",
//            "Spike Chunsoft",
//            "Spil Games",
//            "Spinnaker Software",
//            "Square",
//            "Square Electronic Arts",
//            "Square Enix",
//            "Square Enix Europe",
//            "Stardock",
//            "Starpath",
//            "Stern Electronics",
//            "Sting Entertainment",
//            "Storm Impact",
//            "Strategic Simulations",
//            "Strategic Studies Group",
//            "Stormfront Studios",
//            "Strategy First",
//            "Studio e.go!",
//            "Sublogic",
//            "Success",
//            "Sunflowers Interactive Entertainment Software",
//            "Sunrise Interactive",
//            "Sunsoft",
//            "Superior Software",
//            "Supersoft",
//            "Sydney Development Corporation",
//            "Super Fighter Team",
//            "Suzy Soft",
//            "Synapse Software",
//            "Synergistic Software",
//            "SystemSoft",
//            "System 3",
//            "System Sacom",
//            "Tactics",
//            "Taito",
//            "Takara",
//            "Take-Two Interactive",
//            "TalonSoft",
//            "Tamsoft",
//            "Tandy Corporation",
//            "Taxan",
//            "TDK Mediactive",
//            "Team17",
//            "Team Shanghai Alice",
//            "Techland",
//            "Technical Group Laboratory",
//            "Technology and Entertainment Software",
//            "Technosoft",
//            "Technos Japan",
//            "TecMagik",
//            "Tecmo",
//            "Tectoy",
//            "Telarium",
//            "Telesys",
//            "Telenet Japan",
//            "Telltale Games",
//            "Tencent",
//            "Tengen",
//            "Texas Instruments",
//            "Thalamus Ltd",
//            "Thalion Software",
//            "The9",
//            "The Learning Company",
//            "Thin Chen Enterprise",
//            "Thinking Rabbit",
//            "THQ",
//            "THQ Nordic",
//            "Thorn EMI Computer Software",
//            "Three-Sixty Pacific",
//            "Tiertex Design Studios",
//            "Tiger Electronics",
//            "Time Warner Interactive",
//            "Titus Interactive",
//            "Toaplan",
//            "Toei Animation",
//            "Toho",
//            "Tokuma Shoten",
//            "Tokyo Shoseki",
//            "Tomy",
//            "Tommo",
//            "Tonkin House",
//            "Topologika",
//            "Topo Soft",
//            "TopWare Interactive",
//            "Toshiba EMI",
//            "Towa Chiki",
//            "Tradewest",
//            "Treco",
//            "Triangle Service",
//            "Triffix Entertainment",
//            "Trilobyte Software",
//            "Tripwire Interactive",
//            "Tri Synergy",
//            "Tru Blu Entertainment",
//            "Tsunami Games",
//            "TT Games",
//            "Twilight Frontier",
//            "Tynesoft",
//            "Type-Moon",
//            "Ubisoft",
//            "UEP Systems",
//            "UFO Interactive Games",
//            "Ultimate Play the Game",
//            "Ultrasoft",
//            "Ultra Games",
//            "United States Army",
//            "Universal Entertainment Corporation",
//            "U.S. Gold",
//            "UserJoy Technology",
//            "US Games",
//            "Valcon Games",
//            "Valve",
//            "VAP",
//            "Varie",
//            "VEB Polytechnik",
//            "Vectorbeam",
//            "Viacom",
//            "Victor Interactive",
//            "Vic Tokai",
//            "Virgin Interactive",
//            "Virgin Play",
//            "Virtual Programming",
//            "Visco Corporation",
//            "The Vision Factory",
//            "VisualArt's",
//            "Vivarium Inc.",
//            "Vivendi Games",
//            "Vortex Software",
//            "VoxelStorm",
//            "Vulcan Software",
//            "Wales Interactive",
//            "Walnut Creek CDROM",
//            "Wanadoo Edition",
//            "Warashi",
//            "Wargaming",
//            "Warner Bros. Interactive",
//            "WARP",
//            "Webfoot Technologies",
//            "Webzen",
//            "WildTangent",
//            "Williams Electronics",
//            "Windham Classics",
//            "Windmill",
//            "Windmill Software",
//            "Winkysoft",
//            "Wisdom Tree",
//            "WizardWorks",
//            "Wolf Team",
//            "Working Designs",
//            "Xicat Interactive",
//            "Xonox",
//            "XSEED Games",
//            "XS Games",
//            "Yeti",
//            "Yojigen",
//            "Yonezawa PR21",
            "Yuke's",
            "Yutaka",
            "Zaccaria",
            "ZAPiT Games",
            "ZeniMax Media",
            "Zenobi",
            "Zeppelin Games",
            "Zigurat",
            "Zimag",
            "Zoom",
            "Zuxxez Entertainment",
            "Zushi Games",
            "Zynga",
            "ZyX"
            ]
        );

        $publishers->map(
            fn ($name) => Publisher::factory()->create(
                [
                'name' => $name
                ]
            )
        );
    }
}
